#' Read processed Swift fixes from PinPoint Host software output
#'
#' This function reads the text file generated by the PinPoint Host software and
#'  generates a tidy data frame for further analysis.  The user can optionally
#'  remove unsuccessful fixes.
#'
#' @param swift_txt character scalar or vector containing path(s) to the *.txt file created
#'  by the PinPoint Host software when processing Swift fixes.  Default (`NULL`) prompts the
#'  user to select one or more files.
#' @param out_tz character string indicating the desired output \code{\link[base]{timezone}}
#'  of the GPS fixes.  Datetimes will be converted from the standard GMT time zone of
#'  PinPoint fixes. Default is America/New_York.
#' @param valid_only logical indicating whether unsuccessful GPS fix attempts should be
#'  removed from the output data frame.  The default (FALSE) retains the scheduled fixes
#'  that were unsuccessful.
#' @importFrom lubridate ymd_hms ymd_hm
#' @export

read_pp_swift <- function(swift_txt = NULL, out_tz = "America/New_York", valid_only = FALSE)
{

  if (is.null(swift_txt)) {
    swift_txt <- utils::choose.files(default = "PinPoint", filters = Filters["txt",],
                           caption = "Select .txt files containing processed PinPoint Swift fixes.")
    if (length(swift_txt) == 0) stop("Function cancelled.  No PinPoint output files selected.")
  }
  if (length(swift_txt) == 1) {
    out <- read_tidy_pp(swift_txt, out_tz, valid_only)
  } else {
    out <- lapply(swift_txt, read_tidy_pp, out_tz = out_tz, valid_only = valid_only)
    out <- do.call("rbind", out)
  }
  out
}
