#' Read processed Swift fixes from PinPoint Host software output
#'
#' This function reads the text file generated by the PinPoint Host software and
#'  generates a tidy data frame for further analysis.  The user can optionally
#'  remove unsuccessful fixes.
#'
#' @param swift_txt character path to the *.txt file created by the PinPoint Host
#'  software when processing Swift fixes
#' @param out_tz character string indicating the desired output \code{\link[base]{timezone}}
#'  of the GPS fixes.  Datetimes will be converted from the standard GMT time zone of
#'  PinPoint fixes. Default is America/New_York.
#' @param valid_only logical indicating whether unsuccessful GPS fix attempts should be
#'  removed from the output data frame.  The default (FALSE) retains the scheduled fixes
#'  that were unsuccessful.
#' @export

read_pp_swift <- function(swift_txt, out_tz = "America/New_York", valid_only = FALSE)
{
  out <- suppressWarnings(
    readr::read_fwf(swift_txt, readr::fwf_empty(swift_txt, skip = 1,
                           col_names = c("index", "status", "n_sats", "rtc_date",
                                         "rtc_time", "fix_date", "fix_time", "delta_s",
                                         "lat", "lon", "alt", "hdop", "eres")),
             col_types = "icccccc_ddddd", skip = 1)) %>%
    dplyr::mutate_(
      tag_id = ~ gsub("(^.*PinPoint )(\\d+)( .+$)", "\\2", swift_txt),
      date = ~as.Date(ymd_hms(paste(rtc_date, rtc_time), tz = "GMT"), tz = out_tz),
      sched_local = ~ymd_hm(paste(date, substr(rtc_time, 1, 5)), tz = "GMT"),
      fix_GMT = ~suppressWarnings(ymd_hms(paste(fix_date, fix_time), tz = "GMT")),
      fix_local = ~suppressWarnings(ymd_hms(paste(fix_date, fix_time), tz = "GMT")),
      n_sats = ~sub("/.*", "", n_sats),
      status = ~dplyr::case_when(.$status == "Valid" ~ "valid",
                                 .$status == "NotEnoughSats" ~ "invalid")) %>%
    dplyr::select_(quote(tag_id), quote(status), quote(n_sats), quote(date),
                   quote(sched_local), quote(fix_local), quote(fix_GMT),
                   quote(lat), quote(lon), quote(alt), quote(hdop), quote(eres))
  attr(out$sched_local, "tzone") <- attr(out$fix_local, "tzone") <- out_tz
  if (valid_only) out <- dplyr::filter_(out, ~ status == "valid")
  as.data.frame(out)
}
